sudo: required
language: scala
scala:
- 2.11.11
services:
- docker
env:
  global:
  - TERM=dumb
notifications:
  email: false
install: true
before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_87ffc00cb9e0_key -iv $encrypted_87ffc00cb9e0_iv
  -in tests/credentials.json.enc -out tests/credentials.json -d; fi'
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/deploy_template.sh
  && ./tools/travis/test.sh"